services:
  - type: web
    name: fullstackproject-vrds
    runtime: node
    buildCommand: npm run render-build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: FRONTEND_URL
        value: https://fullstackproject-vrds.onrender.com
      # Database name must be "expense-manager". Collection: "expenses".
      - key: MONGO_URI_PRO
        sync: false
      - key: JWT_SECRET
        sync: false
